// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yogenyslav/loyalty/internal/loyalty/user/orders/controller (interfaces: AccrualService)
//
// Generated by this command:
//
//	mockgen -destination=../../../../../tests/mocks/accrual_service.go -package=mocks . AccrualService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	accrual "github.com/yogenyslav/loyalty/internal/accrual"
	gomock "go.uber.org/mock/gomock"
)

// MockAccrualService is a mock of AccrualService interface.
type MockAccrualService struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualServiceMockRecorder
	isgomock struct{}
}

// MockAccrualServiceMockRecorder is the mock recorder for MockAccrualService.
type MockAccrualServiceMockRecorder struct {
	mock *MockAccrualService
}

// NewMockAccrualService creates a new mock instance.
func NewMockAccrualService(ctrl *gomock.Controller) *MockAccrualService {
	mock := &MockAccrualService{ctrl: ctrl}
	mock.recorder = &MockAccrualServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualService) EXPECT() *MockAccrualServiceMockRecorder {
	return m.recorder
}

// Poll mocks base method.
func (m *MockAccrualService) Poll(ctx context.Context, orders <-chan string, result chan<- accrual.PollResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Poll", ctx, orders, result)
}

// Poll indicates an expected call of Poll.
func (mr *MockAccrualServiceMockRecorder) Poll(ctx, orders, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockAccrualService)(nil).Poll), ctx, orders, result)
}

// PollInterval mocks base method.
func (m *MockAccrualService) PollInterval() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollInterval")
	ret0, _ := ret[0].(int)
	return ret0
}

// PollInterval indicates an expected call of PollInterval.
func (mr *MockAccrualServiceMockRecorder) PollInterval() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollInterval", reflect.TypeOf((*MockAccrualService)(nil).PollInterval))
}

// ProcessOrder mocks base method.
func (m *MockAccrualService) ProcessOrder(ctx context.Context, orderNumber string) (*accrual.AccrualInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessOrder", ctx, orderNumber)
	ret0, _ := ret[0].(*accrual.AccrualInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessOrder indicates an expected call of ProcessOrder.
func (mr *MockAccrualServiceMockRecorder) ProcessOrder(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessOrder", reflect.TypeOf((*MockAccrualService)(nil).ProcessOrder), ctx, orderNumber)
}
