// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yogenyslav/loyalty/internal/loyalty/user/balance/controller (interfaces: balanceRepo)
//
// Generated by this command:
//
//	mockgen -destination=../../../../../tests/mocks/balance_repo.go -package=mocks . balanceRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/yogenyslav/loyalty/internal/loyalty/user/balance/model"
	gomock "go.uber.org/mock/gomock"
)

// MockbalanceRepo is a mock of balanceRepo interface.
type MockbalanceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockbalanceRepoMockRecorder
	isgomock struct{}
}

// MockbalanceRepoMockRecorder is the mock recorder for MockbalanceRepo.
type MockbalanceRepoMockRecorder struct {
	mock *MockbalanceRepo
}

// NewMockbalanceRepo creates a new mock instance.
func NewMockbalanceRepo(ctrl *gomock.Controller) *MockbalanceRepo {
	mock := &MockbalanceRepo{ctrl: ctrl}
	mock.recorder = &MockbalanceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbalanceRepo) EXPECT() *MockbalanceRepoMockRecorder {
	return m.recorder
}

// FindBalanceByUserID mocks base method.
func (m *MockbalanceRepo) FindBalanceByUserID(ctx context.Context, userID int64) (*model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBalanceByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBalanceByUserID indicates an expected call of FindBalanceByUserID.
func (mr *MockbalanceRepoMockRecorder) FindBalanceByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBalanceByUserID", reflect.TypeOf((*MockbalanceRepo)(nil).FindBalanceByUserID), ctx, userID)
}

// InsertWithdrawal mocks base method.
func (m *MockbalanceRepo) InsertWithdrawal(ctx context.Context, userID int64, orderNumber string, amount float64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithdrawal", ctx, userID, orderNumber, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertWithdrawal indicates an expected call of InsertWithdrawal.
func (mr *MockbalanceRepoMockRecorder) InsertWithdrawal(ctx, userID, orderNumber, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithdrawal", reflect.TypeOf((*MockbalanceRepo)(nil).InsertWithdrawal), ctx, userID, orderNumber, amount)
}

// ListWithdrawals mocks base method.
func (m *MockbalanceRepo) ListWithdrawals(ctx context.Context, userID int64) ([]*model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]*model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithdrawals indicates an expected call of ListWithdrawals.
func (mr *MockbalanceRepoMockRecorder) ListWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithdrawals", reflect.TypeOf((*MockbalanceRepo)(nil).ListWithdrawals), ctx, userID)
}

// UpdateBalanceWithdraw mocks base method.
func (m *MockbalanceRepo) UpdateBalanceWithdraw(ctx context.Context, userID int64, withdrawal float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalanceWithdraw", ctx, userID, withdrawal)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalanceWithdraw indicates an expected call of UpdateBalanceWithdraw.
func (mr *MockbalanceRepoMockRecorder) UpdateBalanceWithdraw(ctx, userID, withdrawal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalanceWithdraw", reflect.TypeOf((*MockbalanceRepo)(nil).UpdateBalanceWithdraw), ctx, userID, withdrawal)
}
