// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yogenyslav/loyalty/internal/loyalty/user/auth/controller (interfaces: JwtProvider)
//
// Generated by this command:
//
//	mockgen -destination=../../../../../tests/mocks/jwt.go -package=mocks . JwtProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJwtProvider is a mock of JwtProvider interface.
type MockJwtProvider struct {
	ctrl     *gomock.Controller
	recorder *MockJwtProviderMockRecorder
	isgomock struct{}
}

// MockJwtProviderMockRecorder is the mock recorder for MockJwtProvider.
type MockJwtProviderMockRecorder struct {
	mock *MockJwtProvider
}

// NewMockJwtProvider creates a new mock instance.
func NewMockJwtProvider(ctrl *gomock.Controller) *MockJwtProvider {
	mock := &MockJwtProvider{ctrl: ctrl}
	mock.recorder = &MockJwtProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtProvider) EXPECT() *MockJwtProviderMockRecorder {
	return m.recorder
}

// CreateAccessToken mocks base method.
func (m *MockJwtProvider) CreateAccessToken(userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessToken indicates an expected call of CreateAccessToken.
func (mr *MockJwtProviderMockRecorder) CreateAccessToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessToken", reflect.TypeOf((*MockJwtProvider)(nil).CreateAccessToken), userID)
}
