// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yogenyslav/loyalty/internal/loyalty/user/orders/controller (interfaces: orderRepo,balanceUpdater)
//
// Generated by this command:
//
//	mockgen -destination=../../../../../tests/mocks/order_repo.go -package=mocks . orderRepo,balanceUpdater
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	accrual "github.com/yogenyslav/loyalty/internal/accrual"
	model "github.com/yogenyslav/loyalty/internal/loyalty/user/orders/model"
	database "github.com/yogenyslav/loyalty/pkg/database"
	gomock "go.uber.org/mock/gomock"
)

// MockorderRepo is a mock of orderRepo interface.
type MockorderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockorderRepoMockRecorder
	isgomock struct{}
}

// MockorderRepoMockRecorder is the mock recorder for MockorderRepo.
type MockorderRepoMockRecorder struct {
	mock *MockorderRepo
}

// NewMockorderRepo creates a new mock instance.
func NewMockorderRepo(ctrl *gomock.Controller) *MockorderRepo {
	mock := &MockorderRepo{ctrl: ctrl}
	mock.recorder = &MockorderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderRepo) EXPECT() *MockorderRepoMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockorderRepo) BeginTx(ctx context.Context, level database.TxLevel) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, level)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockorderRepoMockRecorder) BeginTx(ctx, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockorderRepo)(nil).BeginTx), ctx, level)
}

// CommitTx mocks base method.
func (m *MockorderRepo) CommitTx(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTx", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTx indicates an expected call of CommitTx.
func (mr *MockorderRepoMockRecorder) CommitTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTx", reflect.TypeOf((*MockorderRepo)(nil).CommitTx), ctx)
}

// DeletePollingSchedule mocks base method.
func (m *MockorderRepo) DeletePollingSchedule(ctx context.Context, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePollingSchedule", ctx, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePollingSchedule indicates an expected call of DeletePollingSchedule.
func (mr *MockorderRepoMockRecorder) DeletePollingSchedule(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePollingSchedule", reflect.TypeOf((*MockorderRepo)(nil).DeletePollingSchedule), ctx, orderNumber)
}

// FindOrderByNumber mocks base method.
func (m *MockorderRepo) FindOrderByNumber(ctx context.Context, orderNumber string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrderByNumber", ctx, orderNumber)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrderByNumber indicates an expected call of FindOrderByNumber.
func (mr *MockorderRepoMockRecorder) FindOrderByNumber(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrderByNumber", reflect.TypeOf((*MockorderRepo)(nil).FindOrderByNumber), ctx, orderNumber)
}

// FindPollableOrders mocks base method.
func (m *MockorderRepo) FindPollableOrders(ctx context.Context) ([]*model.PollableOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPollableOrders", ctx)
	ret0, _ := ret[0].([]*model.PollableOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPollableOrders indicates an expected call of FindPollableOrders.
func (mr *MockorderRepoMockRecorder) FindPollableOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPollableOrders", reflect.TypeOf((*MockorderRepo)(nil).FindPollableOrders), ctx)
}

// InsertOrder mocks base method.
func (m *MockorderRepo) InsertOrder(ctx context.Context, order *model.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrder", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrder indicates an expected call of InsertOrder.
func (mr *MockorderRepoMockRecorder) InsertOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrder", reflect.TypeOf((*MockorderRepo)(nil).InsertOrder), ctx, order)
}

// ListOrders mocks base method.
func (m *MockorderRepo) ListOrders(ctx context.Context, userID int64) ([]*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", ctx, userID)
	ret0, _ := ret[0].([]*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockorderRepoMockRecorder) ListOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockorderRepo)(nil).ListOrders), ctx, userID)
}

// RollbackTx mocks base method.
func (m *MockorderRepo) RollbackTx(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTx", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTx indicates an expected call of RollbackTx.
func (mr *MockorderRepoMockRecorder) RollbackTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTx", reflect.TypeOf((*MockorderRepo)(nil).RollbackTx), ctx)
}

// SchedulePolling mocks base method.
func (m *MockorderRepo) SchedulePolling(ctx context.Context, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchedulePolling", ctx, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// SchedulePolling indicates an expected call of SchedulePolling.
func (mr *MockorderRepoMockRecorder) SchedulePolling(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchedulePolling", reflect.TypeOf((*MockorderRepo)(nil).SchedulePolling), ctx, orderNumber)
}

// UpdateOrderAfterPolling mocks base method.
func (m *MockorderRepo) UpdateOrderAfterPolling(ctx context.Context, data *accrual.AccrualInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderAfterPolling", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderAfterPolling indicates an expected call of UpdateOrderAfterPolling.
func (mr *MockorderRepoMockRecorder) UpdateOrderAfterPolling(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderAfterPolling", reflect.TypeOf((*MockorderRepo)(nil).UpdateOrderAfterPolling), ctx, data)
}

// UpdatePollingSchedule mocks base method.
func (m *MockorderRepo) UpdatePollingSchedule(ctx context.Context, orderNumber string, backoffSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePollingSchedule", ctx, orderNumber, backoffSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePollingSchedule indicates an expected call of UpdatePollingSchedule.
func (mr *MockorderRepoMockRecorder) UpdatePollingSchedule(ctx, orderNumber, backoffSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePollingSchedule", reflect.TypeOf((*MockorderRepo)(nil).UpdatePollingSchedule), ctx, orderNumber, backoffSeconds)
}

// MockbalanceUpdater is a mock of balanceUpdater interface.
type MockbalanceUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockbalanceUpdaterMockRecorder
	isgomock struct{}
}

// MockbalanceUpdaterMockRecorder is the mock recorder for MockbalanceUpdater.
type MockbalanceUpdaterMockRecorder struct {
	mock *MockbalanceUpdater
}

// NewMockbalanceUpdater creates a new mock instance.
func NewMockbalanceUpdater(ctrl *gomock.Controller) *MockbalanceUpdater {
	mock := &MockbalanceUpdater{ctrl: ctrl}
	mock.recorder = &MockbalanceUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbalanceUpdater) EXPECT() *MockbalanceUpdaterMockRecorder {
	return m.recorder
}

// UpdateBalanceAccrual mocks base method.
func (m *MockbalanceUpdater) UpdateBalanceAccrual(ctx context.Context, userID int64, arg2 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalanceAccrual", ctx, userID, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalanceAccrual indicates an expected call of UpdateBalanceAccrual.
func (mr *MockbalanceUpdaterMockRecorder) UpdateBalanceAccrual(ctx, userID, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalanceAccrual", reflect.TypeOf((*MockbalanceUpdater)(nil).UpdateBalanceAccrual), ctx, userID, arg2)
}
