// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yogenyslav/loyalty/internal/loyalty/user/auth/controller (interfaces: userRepo,userBalanceRepo)
//
// Generated by this command:
//
//	mockgen -destination=../../../../../tests/mocks/user_repo.go -package=mocks . userRepo,userBalanceRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/yogenyslav/loyalty/internal/loyalty/user/auth/model"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepo is a mock of userRepo interface.
type MockuserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepoMockRecorder
	isgomock struct{}
}

// MockuserRepoMockRecorder is the mock recorder for MockuserRepo.
type MockuserRepoMockRecorder struct {
	mock *MockuserRepo
}

// NewMockuserRepo creates a new mock instance.
func NewMockuserRepo(ctrl *gomock.Controller) *MockuserRepo {
	mock := &MockuserRepo{ctrl: ctrl}
	mock.recorder = &MockuserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepo) EXPECT() *MockuserRepoMockRecorder {
	return m.recorder
}

// FindUserByLogin mocks base method.
func (m *MockuserRepo) FindUserByLogin(ctx context.Context, login string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByLogin", ctx, login)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByLogin indicates an expected call of FindUserByLogin.
func (mr *MockuserRepoMockRecorder) FindUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByLogin", reflect.TypeOf((*MockuserRepo)(nil).FindUserByLogin), ctx, login)
}

// InsertUser mocks base method.
func (m *MockuserRepo) InsertUser(ctx context.Context, u *model.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", ctx, u)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockuserRepoMockRecorder) InsertUser(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockuserRepo)(nil).InsertUser), ctx, u)
}

// MockuserBalanceRepo is a mock of userBalanceRepo interface.
type MockuserBalanceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockuserBalanceRepoMockRecorder
	isgomock struct{}
}

// MockuserBalanceRepoMockRecorder is the mock recorder for MockuserBalanceRepo.
type MockuserBalanceRepoMockRecorder struct {
	mock *MockuserBalanceRepo
}

// NewMockuserBalanceRepo creates a new mock instance.
func NewMockuserBalanceRepo(ctrl *gomock.Controller) *MockuserBalanceRepo {
	mock := &MockuserBalanceRepo{ctrl: ctrl}
	mock.recorder = &MockuserBalanceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserBalanceRepo) EXPECT() *MockuserBalanceRepoMockRecorder {
	return m.recorder
}

// InsertBalance mocks base method.
func (m *MockuserBalanceRepo) InsertBalance(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBalance", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBalance indicates an expected call of InsertBalance.
func (mr *MockuserBalanceRepoMockRecorder) InsertBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBalance", reflect.TypeOf((*MockuserBalanceRepo)(nil).InsertBalance), ctx, userID)
}
