name: loyalty

volumes:
  pg_data:

services:
  pg:
    image: postgres:17
    restart: unless-stopped
    container_name: loyalty-pg
    environment:
      - POSTGRES_USER=${DB_USER:-pguser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-pgpass}
      - POSTGRES_DB=${DB_NAME:-dev}
    ports:
      - "5432:${DB_PORT:-5432}"
    volumes:
      - pg_data:/var/lib/postgresql/data
