name: loyalty

volumes:
  pg_data:

services:
  pg:
    image: postgres:17
    restart: unless-stopped
    container_name: loyalty-pg
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pguser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpass}
      - POSTGRES_DB=${POSTGRES_DB:-dev}
    ports:
      - "5432:${POSTGRES_PORT:-5432}"
    volumes:
      - pg_data:/var/lib/postgresql/data
